# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/bundles/ckeditor_mybuild"
    js_path:   "build/bundles/ckeditor_mybuild/ckeditor.js"
    configs:
        my_config:
            language: fr
            uiColor:                "#000000"
#            toolbar: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ]
            toolbar: null
            codeSnippet_theme: 'railscasts'
            codeSnippet_languages:
                - 'PHP'
                - 'SQL'
                - 'JavaScript'
                - 'HTML'
                - 'Twig'
                - 'css'
                - 'scss'
                - 'Clingon'
